coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      default:
        target: 70%
        threshold: 1%

ignore:
  - "backend/cmd/server/main.go"
  - "backend/db/**/*"
  - "backend/services/mock/**/*"
  
comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false