coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      default:
        target: 70%
        threshold: 1%

ignore:
  - "backend/main.go"
  - "backend/db/mock/**/*"
  - "backend/db/sqlc/**/*"
  - "backend/db/migrations/**/*"
  
comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false