-- +goose Up
-- +goose StatementBegin
-- First update any creature names that have changed
UPDATE creatures SET name = 'Nomad (Female)' WHERE name = 'Nomad  (Female)';
UPDATE creatures SET name = 'Nomad (Blue)' WHERE name = 'Nomad  (Blue)';
UPDATE creatures SET name = 'Nomad' WHERE name = 'Nomad  (Basic)';
UPDATE creatures SET name = 'Butterfly (Red)' WHERE name = 'Butterfly  (Red)';
UPDATE creatures SET name = 'Butterfly (Purple)' WHERE name = 'Butterfly  (Purple)';
UPDATE creatures SET name = 'Butterfly (Blue)' WHERE name = 'Butterfly  (Blue)';
UPDATE creatures SET name = 'Horse (Gray)' WHERE name = 'Horse  (Gray)';
UPDATE creatures SET name = 'Horse (Brown)' WHERE name = 'Horse  (Brown)';
UPDATE creatures SET name = 'Horse (Dark Brown)' WHERE name = 'Horse  (Taupe)';

-- Add difficulty column
ALTER TABLE creatures ADD COLUMN difficulty INTEGER;

-- Update difficulties from the JSON data
UPDATE creatures c
SET difficulty = d.difficulty
FROM (
    VALUES 
        ('Askarak Lord', 3),
        ('Damaged Crystal Golem', 3),
        ('Floating Savant', 4),
        ('Minotaur Archer', 2),
        ('Priestess', 3),
        ('Minotaur Invader', 3),
        ('Ghoul', 2),
        ('Wiggler', 3),
        ('Witch', 2),
        ('Golden Servant Replica', 3),
        ('Falcon Knight', 4),
        ('Deepling Warrior', 3),
        ('Green Djinn', 3),
        ('Orc Warrior', 2),
        ('Green Frog', 1),
        ('Waspoid', 3),
        ('Dragolisk', 4),
        ('Gorger Inferniarch', 4),
        ('Cyclops Drone', 3),
        ('Killer Rabbit', 2),
        ('Poisonous Carnisylvan', 4),
        ('Cursed Book', 3),
        ('Nightslayer', 3),
        ('Execowtioner', 3),
        ('Streaked Devourer', 4),
        ('Agrestic Chicken', 1),
        ('Rootthing Amber Shaper', 3),
        ('Spidris', 3),
        ('Spectre', 3),
        ('Slug', 2),
        ('Adult Goanna', 4),
        ('Raging Fire', 3),
        ('Orewalker', 4),
        ('Ice Golem', 3),
        ('Pirat Scoundrel', 3),
        ('Golden Servant', 3),
        ('Skeleton Elite Warrior', 3),
        ('White Weretiger', 4),
        ('Lizard Snakecharmer', 3),
        ('Deepling Tyrant', 4),
        ('Winter Wolf', 1),
        ('Gloom Wolf', 2),
        ('Terramite', 2),
        ('Draken Spellweaver', 3),
        ('Wyvern', 3),
        ('Sparkion', 4),
        ('Menacing Carnivor', 4),
        ('Rabbit', 1),
        ('Hibernal Moth', 3),
        ('Worm Priestess', 3),
        ('Stonerefiner', 3),
        ('Stalker', 2),
        ('Phantasm', 4),
        ('Boar', 2),
        ('Rotworm', 2),
        ('Broodrider Inferniarch', 4),
        ('Crystal Wolf', 3),
        ('Ogre Sage', 4),
        ('Hellspawn', 3),
        ('Haunted Treeling', 3),
        ('Quara Predator', 3),
        ('Werefox', 3),
        ('Shock Head', 3),
        ('Barkless Devotee', 3),
        ('Ice Witch', 3),
        ('Clay Guardian', 3),
        ('Branchy Crawler', 5),
        ('Truffle Cook', 3),
        ('Goblin Assassin', 3),
        ('Vexclaw', 3),
        ('Grim Reaper', 4),
        ('Mooh''Tah Warrior', 3),
        ('Bog Raider', 3),
        ('Renegade Quara Constrictor', 3),
        ('Candy Floss Elemental', 4),
        ('Elf Arcanist', 3),
        ('Rotten Golem', 3),
        ('Renegade Quara Mantassin', 3),
        ('Assassin', 2),
        ('Falcon Paladin', 4),
        ('Capricious Phantom', 5),
        ('Dragonling', 3),
        ('Bellicose Orger', 3),
        ('Ghastly Dragon', 3),
        ('Bulltaur Brute', 4),
        ('Yeti', 3),
        ('Crocodile', 2),
        ('Crypt Warrior', 4),
        ('Furious Fire Elemental', 3),
        ('Lost Berserker', 3),
        ('Werelioness', 4),
        ('Lizard Dragon Priest', 3),
        ('Adventurer', 2),
        ('Nomad (Female)', 2),
        ('Quara Raider', 3),
        ('Deepling Brawler', 3),
        ('Azure Frog', 2),
        ('Chicken', 1),
        ('War Golem', 3),
        ('Feral Sphinx', 4),
        ('Evil Prospector', 3),
        ('Barkless Fanatic', 3),
        ('Liodile', 3),
        ('Deepling Master Librarian', 3),
        ('Vicious Squire', 3),
        ('Panda', 2),
        ('Lacewing Moth', 3),
        ('Iron Servant', 2),
        ('Albino Dragon', 3),
        ('Lamassu', 4),
        ('Tomb Servant', 3),
        ('Pirat Bombardier', 3),
        ('Cunning Werepanther', 4),
        ('Swan Maiden', 3),
        ('Dark Faun', 3),
        ('Enraged Crystal Golem', 3),
        ('Minotaur Cult Zealot', 3),
        ('Bane of Light', 3),
        ('Lost Basher', 3),
        ('Damaged Worker Golem', 3),
        ('Energetic Book', 3),
        ('Bat', 1),
        ('Cursed Prospector', 3),
        ('Elf', 2),
        ('Iks Chuka', 3),
        ('Shaburak Lord', 3),
        ('Frost Giant', 2),
        ('Troll Champion', 3),
        ('Juvenile Bashmu', 4),
        ('Spellreaper Inferniarch', 4),
        ('Tarantula', 3),
        ('Orc Spearman', 2),
        ('Hellfire Fighter', 4),
        ('Troll Guard', 3),
        ('Enfeebled Silencer', 3),
        ('Hero', 3),
        ('Silver Rabbit', 2),
        ('Wild Warrior', 2),
        ('Yielothax', 3),
        ('Cobra Scout', 4),
        ('Eyeless Devourer', 4),
        ('Little Corym Charlatan', 2),
        ('Son of Verminor', 4),
        ('Leaf Golem', 3),
        ('Shrieking Cry-Stal', 3),
        ('Sacred Spider', 3),
        ('Quara Hydromancer Scout', 3),
        ('Tiger', 2),
        ('Parrot', 1),
        ('Energy Elemental', 3),
        ('Stone Rhino', 3),
        ('Angry Sugar Fairy', 4),
        ('Walker', 3),
        ('Crazed Beggar', 2),
        ('Dwarf Soldier', 2),
        ('Ripper Spectre', 3),
        ('Spitter', 3),
        ('Orc Cult Priest', 3),
        ('Boogy', 3),
        ('Candy Horror', 4),
        ('Sugar Cube Worker', 0),
        ('Vampire', 3),
        ('Blood Priest', 3),
        ('Fruit Drop', 0),
        ('Chocolate Blob', 0),
        ('Poacher', 2),
        ('Deathling Scout', 3),
        ('Schiach', 3),
        ('Quara Plunderer', 3),
        ('Infernal Frog', 3),
        ('Vulcongra', 3),
        ('Instable Breach Brood', 3),
        ('Thanatursus', 3),
        ('Quara Pincher Scout', 3),
        ('Meandering Mushroom', 5),
        ('Pirat Cutthroat', 3),
        ('Silencer', 3),
        ('Soul-Broken Harbinger', 3),
        ('Tremendous Tyrant', 3),
        ('Manta Ray', 3),
        ('Orclops Doomhauler', 3),
        ('Terrified Elephant', 3),
        ('Glooth Blob', 3),
        ('Flamingo', 1),
        ('Skeleton Warrior', 2),
        ('Crustacea Gigantica', 3),
        ('Deepling Spellsinger', 3),
        ('Marsh Stalker', 2),
        ('Ink Blob', 4),
        ('Pirate Corsair', 3),
        ('Dromedary', 1),
        ('Spit Nettle', 2),
        ('Pirate Buccaneer', 3),
        ('Cult Enforcer', 3),
        ('Bog Frog', 1),
        ('Nomad (Blue)', 2),
        ('Rootthing Nutshell', 3),
        ('Nightstalker', 3),
        ('Ironblight', 4),
        ('Roaring Lion', 3),
        ('Nymph', 3),
        ('Loricate Orger', 3),
        ('Darklight Source', 3),
        ('Ogre Shaman', 3),
        ('Headpecker', 5),
        ('Warlock', 3),
        ('Barbarian Bloodwalker', 3),
        ('Cave Chimera', 4),
        ('Orc Leader', 3),
        ('Gargoyle', 3),
        ('Pirate Skeleton', 2),
        ('Behemoth', 3),
        ('Crypt Defiler', 2),
        ('Dragon Lord', 3),
        ('Ladybug', 1),
        ('Many Faces', 5),
        ('Lizard Chosen', 3),
        ('Weeper', 4),
        ('Coral Frog', 2),
        ('Gozzler', 3),
        ('Baleful Bunny', 3),
        ('Retching Horror', 3),
        ('Hand of Cursed Fate', 4),
        ('Undead Mine Worker', 3),
        ('Draken Elite', 3),
        ('Plaguesmith', 3),
        ('Deepling Elite', 3),
        ('Evil Sheep Lord', 3),
        ('Demon Outcast', 3),
        ('Minotaur Hunter', 3),
        ('Humongous Fungus', 4),
        ('Eternal Guardian', 3),
        ('Cloak of Terror', 5),
        ('Water Buffalo', 2),
        ('Feversleep', 3),
        ('Bane Bringer', 3),
        ('Boar Man', 4),
        ('Deepling Worker', 2),
        ('Sopping Corpus', 5),
        ('Filth Toad', 2),
        ('Starving Wolf', 2),
        ('Shadow Hound', 3),
        ('Usurper Knight', 3),
        ('Grynch Clan Goblin', 1),
        ('Renegade Quara Hydromancer', 3),
        ('Quara Hydromancer', 3),
        ('Sulphur Spouter', 3),
        ('Crazed Summer Vanguard', 4),
        ('Instable Sparkion', 3),
        ('Makara', 4),
        ('Lizard Sentinel', 3),
        ('Stabilizing Reality Reaver', 3),
        ('Sandstone Scorpion', 3),
        ('Bride of Night', 3),
        ('Distorted Phantom', 3),
        ('Dire Penguin', 3),
        ('Gingerbread Man', 2),
        ('Sheep', 1),
        ('Stalking Stalk', 5),
        ('Ghost Wolf', 2),
        ('Goldhanded Cultist', 3),
        ('Insectoid Scout', 2),
        ('Seacrest Serpent', 3),
        ('Varnished Diremaw', 3),
        ('Truffle', 3),
        ('Insectoid Worker', 3),
        ('Sugar Cube', 0),
        ('Crape Man', 4),
        ('Twisted Shaper', 3),
        ('Smuggler', 2),
        ('Animated Feather', 4),
        ('Vibrant Phantom', 3),
        ('Juggernaut', 4),
        ('Dread Intruder', 3),
        ('Terrorsleep', 3),
        ('Corym Skirmisher', 3),
        ('Carniphila', 3),
        ('Feverish Citizen', 2),
        ('Draken Abomination', 3),
        ('Werewolf', 3),
        ('Devourer', 3),
        ('Squidgy Slime', 2),
        ('Werelion', 4),
        ('Iks Ahpututu', 3),
        ('Girtablilu Warrior', 3),
        ('Salamander', 3),
        ('Weakened Frazzlemaw', 3),
        ('Biting Book', 4),
        ('Defiler', 3),
        ('Sea Serpent', 3),
        ('Duskbringer', 3),
        ('Sight of Surrender', 3),
        ('Walking Pillar', 3),
        ('Wandering Pillar', 3),
        ('Poison Spider', 1),
        ('Massive Energy Elemental', 3),
        ('Draken Warmaster', 3),
        ('Butterfly (Red)', 1),
        ('Frost Dragon Hatchling', 3),
        ('Darklight Emitter', 3),
        ('Minotaur Amazon', 4),
        ('Hot Dog', 3),
        ('Mitmah Scout', 3),
        ('Mad Scientist', 2),
        ('Minotaur Cult Follower', 3),
        ('Vampire Bride', 3),
        ('Amazon', 2),
        ('Stampor', 3),
        ('Iron Servant Replica', 3),
        ('Corym Charlatan', 2),
        ('Nightmare', 3),
        ('Wisp', 1),
        ('Haunted Dragon', 4),
        ('Massive Water Elemental', 3),
        ('Diamond Servant Replica', 3),
        ('Undead Gladiator', 3),
        ('Noble Lion', 3),
        ('Dragon Hatchling', 3),
        ('Killer Caiman', 3),
        ('Frost Flower Asura', 3),
        ('Blemished Spawn', 4),
        ('Askarak Demon', 3),
        ('Mitmah Seer', 3),
        ('Clomp', 3),
        ('Orc Cult Inquisitor', 3),
        ('Sabretooth', 3),
        ('Rotten Man-Maggot', 3),
        ('Deepworm', 3),
        ('Emerald Damselfly', 2),
        ('Pirate Marauder', 2),
        ('Forest Fury', 3),
        ('Dark Carnisylvan', 4),
        ('True Midnight Asura', 3),
        ('Demon Parrot', 3),
        ('Vicious Manbat', 3),
        ('Monk''s Apparition', 3),
        ('Kongra', 3),
        ('Mantosaurus', 5),
        ('Firestarter', 2),
        ('Sandcrawler', 3),
        ('Dworc Fleshhunter', 2),
        ('Butterfly (Purple)', 1),
        ('Lavaworm', 3),
        ('Dragon Lord Hatchling', 3),
        ('Bonelord', 2),
        ('Gang Member', 2),
        ('Lion', 3),
        ('Iks Aucar', 3),
        ('Orc Warlord', 3),
        ('Ravenous Lava Lurker', 3),
        ('Cult Believer', 3),
        ('Lich', 3),
        ('Sibang', 3),
        ('Young Sea Serpent', 3),
        ('Mushroom Sniffer', 2),
        ('Bulltaur Forgepriest', 4),
        ('Twisted Pooka', 3),
        ('Mutated Tiger', 3),
        ('Shark', 3),
        ('Toad', 1),
        ('Rustheap Golem', 3),
        ('Valkyrie', 3),
        ('Sorcerer''s Apparition', 5),
        ('Pigeon', 0),
        ('Dragon', 3),
        ('Dwarf Geomancer', 3),
        ('Gore Horn', 3),
        ('Troll', 2),
        ('Crystalcrusher', 3),
        ('Blood Beast', 3),
        ('Druid''s Apparition', 3),
        ('Barbarian Skullhunter', 2),
        ('Glooth Anemone', 3),
        ('Lizard Magistratus', 3),
        ('Cow', 3),
        ('Wafer Paper Butterfly', 3),
        ('Horse (Gray)', 1),
        ('Ancient Scarab', 3),
        ('Goblin Leader', 3),
        ('Orc Berserker', 3),
        ('Water Elemental', 3),
        ('Chakoya Tribewarden', 2),
        ('Pixie', 3),
        ('Insect Swarm', 2),
        ('Flying Book', 3),
        ('Acolyte of Darkness', 2),
        ('Banshee', 3),
        ('Midnight Spawn', 3),
        ('Lost Thrower', 3),
        ('Werepanther', 4),
        ('Shaburak Demon', 3),
        ('Burning Gladiator', 4),
        ('Squirrel', 1),
        ('Elf Overseer', 3),
        ('Mould Phantom', 3),
        ('Exotic Cave Spider', 3),
        ('Roast Pork', 3),
        ('White Deer', 1),
        ('Slime', 1),
        ('Furious Troll', 2),
        ('Grave Robber', 2),
        ('Elder Wyrm', 3),
        ('Dryad', 3),
        ('Glooth Bandit', 3),
        ('Ragged Rabid Wolf', 3),
        ('Deathling Spellsinger', 3),
        ('Renegade Quara Predator', 3),
        ('Frazzlemaw', 4),
        ('Fire Devil', 2),
        ('Husky', 0),
        ('Death Blob', 3),
        ('Harpy', 4),
        ('Quara Predator Scout', 3),
        ('Blood Hand', 3),
        ('Kollos', 3),
        ('Werecrocodile', 4),
        ('Elephant', 2),
        ('Bony Sea Devil', 5),
        ('Moohtant', 3),
        ('Undead Prospector', 3),
        ('Quara Mantassin Scout', 3),
        ('Mutated Human', 3),
        ('Infected Weeper', 4),
        ('Berrypest', 0),
        ('Emerald Tortoise', 2),
        ('Ghoulish Hyaena', 3),
        ('Rabid Wolf', 2),
        ('Frost Giantess', 2),
        ('Worker Golem', 3),
        ('Faun', 3),
        ('Usurper Warlock', 3),
        ('Lizard Templar', 3),
        ('Deepling Scout', 2),
        ('Cave Rat', 1),
        ('Nomad', 2),
        ('Skunk', 1),
        ('Omnivora', 3),
        ('Scorpion', 2),
        ('Brachiodemon', 5),
        ('Spidris Elite', 3),
        ('Shaper Matriarch', 3),
        ('Lava Lurker', 3),
        ('Sulphider', 5),
        ('Dark Monk', 3),
        ('Mammoth', 2),
        ('Blood Crab', 2),
        ('Nightfiend', 3),
        ('Butterfly (Blue)', 1),
        ('Renegade Quara Pincher', 3),
        ('Glooth Brigand', 3),
        ('Breach Brood', 4),
        ('Insane Siren', 4),
        ('Pooka', 3),
        ('Tortoise', 2),
        ('Vile Grandmaster', 3),
        ('Brinebrute Inferniarch', 4),
        ('Orchid Frog', 2),
        ('Enlightened of the Cult', 3),
        ('Afflicted Strider', 4),
        ('Lizard High Guard', 3),
        ('Ice Dragon', 3),
        ('Goblin', 2),
        ('Calamary', 2),
        ('Mercury Blob', 2),
        ('Ogre Brute', 3),
        ('Bashmu', 4),
        ('Wolf', 1),
        ('Nighthunter', 3),
        ('Hulking Prehemoth', 5),
        ('Grave Guard', 3),
        ('Darklight Construct', 3),
        ('Iks Pututu', 3),
        ('Crypt Warden', 4),
        ('Chakoya Toolshaper', 2),
        ('Dwarf Guard', 2),
        ('Dark Torturer', 3),
        ('Undertaker', 3),
        ('Death Priest', 3),
        ('Zombie', 2),
        ('Earth Elemental', 3),
        ('Orc Rider', 2),
        ('Courage Leech', 5),
        ('Guardian of Tales', 4),
        ('Skeleton', 2),
        ('Gorerilla', 3),
        ('Deepling Guard', 2),
        ('Pig', 1),
        ('Quara Pincher', 3),
        ('Hydra', 3),
        ('Chakoya Windcaller', 2),
        ('Gnarlhound', 3),
        ('Werebear', 3),
        ('Carnivostrich', 4),
        ('Cursed Ape', 3),
        ('Doom Deer', 3),
        ('Midnight Asura', 3),
        ('Cyclops Smith', 3),
        ('Weretiger', 4),
        ('Destroyer', 3),
        ('Doomsday Cultist', 3),
        ('Hellhunter Inferniarch', 4),
        ('Swampling', 3),
        ('Cave Parrot', 1),
        ('Deer', 1),
        ('Snake', 1),
        ('Merlkin', 2),
        ('Iks Yapunac', 4),
        ('Black Sheep', 1),
        ('Werebadger', 3),
        ('Bulltaur Alchemist', 4),
        ('Dark Apprentice', 3),
        ('Hyaena', 2),
        ('Fire Elemental', 3),
        ('Mega Dragon', 4),
        ('Berserker Chicken', 3),
        ('Wardragon', 3),
        ('Two-Headed Turtle', 3),
        ('Vampire Viscount', 3),
        ('Jellyfish', 2),
        ('Exotic Bat', 3),
        ('Armadile', 4),
        ('Dog', 1),
        ('Elder Forest Fury', 3),
        ('Young Goanna', 3),
        ('Adept of the Cult', 3),
        ('Vampire Pig', 3),
        ('Horse (Brown)', 1),
        ('Nibblemaw', 3),
        ('Hellflayer', 4),
        ('Parder', 3),
        ('Cream Blob', 0),
        ('Burning Book', 4),
        ('Bloated Man-Maggot', 5),
        ('Crystal Spider', 3),
        ('Massive Fire Elemental', 3),
        ('Goggle Cake', 2),
        ('Cake Golem', 2),
        ('Wasp', 1),
        ('Hunter', 2),
        ('Naga Warrior', 3),
        ('Novice of the Cult', 2),
        ('Usurper Archer', 3),
        ('Fish', 1),
        ('Blightwalker', 4),
        ('Ogre Rowdy', 4),
        ('Mutated Rat', 3),
        ('Choking Fear', 4),
        ('White Shade', 2),
        ('Foam Stalker', 4),
        ('Rootthing Bug Tracker', 3),
        ('Cult Scholar', 3),
        ('Converter', 5),
        ('Northern Pike', 0),
        ('Goldhanded Cultist Bride', 3),
        ('Demon', 3),
        ('Mercurial Menace', 5),
        ('Darklight Matter', 3),
        ('Hellhound', 4),
        ('Renegade Knight', 3),
        ('Lavafungus', 3),
        ('Knowledge Elemental', 3),
        ('Flimsy Lost Soul', 4),
        ('Oozing Corpus', 5),
        ('Terror Bird', 3),
        ('Wyrm', 3),
        ('Putrid Mummy', 3),
        ('Honour Guard', 2),
        ('Swamp Troll', 3),
        ('Rorc', 3),
        ('Animated Snowman', 3),
        ('Midnight Warrior', 3),
        ('Orc Shaman', 2),
        ('Dworc Venomsniper', 2),
        ('Scarab', 2),
        ('Werehyaena Shaman', 3),
        ('Venerable Girtablilu', 3),
        ('Stabilizing Dread Intruder', 3),
        ('Ominous', 3),
        ('Wild Horse', 1),
        ('Shadow Pupil', 3),
        ('Midnight Panther', 3),
        ('Swarmer', 3),
        ('Quara Mantassin', 3),
        ('Mole', 1),
        ('Sineater Inferniarch', 3),
        ('Spider', 1),
        ('Carrion Worm', 2),
        ('Medusa', 4),
        ('Turbulent Elemental', 3),
        ('Efreet', 3),
        ('Polar Bear', 2),
        ('Black Sphinx Acolyte', 4),
        ('Gryphon', 3),
        ('Quara Looter', 4),
        ('Diabolic Imp', 3),
        ('Tarnished Spirit', 3),
        ('Lava Golem', 3),
        ('Orc Cultist', 3),
        ('Enslaved Dwarf', 3),
        ('Broken Shaper', 3),
        ('Gravedigger', 3),
        ('Badger', 1),
        ('Centipede', 2),
        ('Barbarian Brutetamer', 2),
        ('Lizard Zaogun', 3),
        ('Brain Squid', 4),
        ('Goblin Scavenger', 2),
        ('Lizard Noble', 3),
        ('White Lion', 4),
        ('Orc Cult Fanatic', 3),
        ('Arachnophobica', 4),
        ('Stone Golem', 2),
        ('Sopping Carcass', 5),
        ('Cobra Assassin', 4),
        ('Knight''s Apparition', 3),
        ('Minotaur', 2),
        ('Island Troll', 1),
        ('Iks Churrascan', 3),
        ('Undead Elite Gladiator', 3),
        ('Infernalist', 4),
        ('Infernal Phantom', 5),
        ('Undead Jester', 3),
        ('Penguin', 1),
        ('Cliff Strider', 4),
        ('Orger', 3),
        ('Fox', 1),
        ('Lost Soul', 3),
        ('Darklight Striker', 3),
        ('Hideous Fungus', 4),
        ('Lost Husher', 3),
        ('Guzzlemaw', 4),
        ('True Dawnfire Asura', 3),
        ('Noxious Ripptor', 5),
        ('Ghost', 2),
        ('Redeemed Soul', 3),
        ('Demon Skeleton', 3),
        ('Rhindeer', 3),
        ('Lumbering Carnivor', 3),
        ('Cobra', 2),
        ('Mutated Bat', 3),
        ('Draptor', 3),
        ('Orclops Ravager', 3),
        ('Manticore', 4),
        ('Mummy', 3),
        ('Undead Dragon', 3),
        ('Grimeleech', 4),
        ('Hive Overseer', 4),
        ('Misguided Bully', 3),
        ('Feral Werecrocodile', 4),
        ('Oozing Carcass', 5),
        ('Modified Gnarlhound', 3),
        ('Gazer', 3),
        ('Cat', 0),
        ('Elder Mummy', 3),
        ('White Tiger', 1),
        ('Thornfire Wolf', 3),
        ('Sphinx', 4),
        ('Barbarian Headsplitter', 2),
        ('Squid Warden', 4),
        ('Icecold Book', 4),
        ('Jungle Moa', 3),
        ('Ogre Ruffian', 4),
        ('Dark Magician', 3),
        ('Chasm Spawn', 4),
        ('True Frost Flower Asura', 3),
        ('Wereboar', 3),
        ('Bug', 1),
        ('Nightmare Scion', 3),
        ('Betrayed Wraith', 3),
        ('Undead Cavebear', 3),
        ('Orc Cult Minion', 3),
        ('Minotaur Cult Prophet', 3),
        ('Elder Bonelord', 3),
        ('Pirate Ghost', 2),
        ('Abyssal Calamary', 2),
        ('Misguided Thief', 3),
        ('Spiky Carnivor', 4),
        ('Glooth Golem', 3),
        ('Minotaur Guard', 3),
        ('Arctic Faun', 3),
        ('Thornback Tortoise', 3),
        ('Diremaw', 3),
        ('Frost Dragon', 3),
        ('Acid Blob', 3),
        ('War Wolf', 3),
        ('Tainted Soul', 3),
        ('Stone Devourer', 4),
        ('Braindeath', 3),
        ('Seagull', 1),
        ('Rage Squid', 3),
        ('Serpent Spawn', 3),
        ('Honey Elemental', 1),
        ('Diamond Servant', 3),
        ('Monk', 3),
        ('Rot Elemental', 3),
        ('Magma Crawler', 4),
        ('Deepsea Blood Crab', 3),
        ('Tunnel Tyrant', 3),
        ('Gazer Spectre', 3),
        ('Crab', 2),
        ('Bonebeast', 3),
        ('Giant Spider', 3),
        ('Necromancer', 3),
        ('Lost Exile', 3),
        ('Marid', 3),
        ('Pirat Mate', 3),
        ('Crazed Winter Rearguard', 3),
        ('Elf Scout', 2),
        ('Wailing Widow', 3),
        ('Naga Archer', 3),
        ('Orc Marauder', 3),
        ('Troll Legionnaire', 3),
        ('Mean Lost Soul', 4),
        ('Drillworm', 3),
        ('Crimson Frog', 2),
        ('Massive Earth Elemental', 3),
        ('Cobra Vizier', 4),
        ('Dwarf Henchman', 2),
        ('Lizard Legionnaire', 3),
        ('Corym Vanguard', 3),
        ('Ogre Savage', 3),
        ('Infernal Demon', 5),
        ('Brimstone Bug', 3),
        ('High Voltage Elemental', 3),
        ('Werehyaena', 3),
        ('Dawnfire Asura', 3),
        ('Bear', 2),
        ('Freakish Lost Soul', 4),
        ('Wilting Leaf Golem', 3),
        ('Fury', 3),
        ('Larva', 1),
        ('Crazed Winter Vanguard', 3),
        ('Crypt Shambler', 2),
        ('Quara Constrictor', 3),
        ('Crawler', 3),
        ('Blue Djinn', 3),
        ('Energuardian of Tales', 3),
        ('Mycobiontic Beetle', 3),
        ('Cyclops', 2),
        ('Horse (Dark Brown)', 1),
        ('Rat', 1),
        ('Lancer Beetle', 3),
        ('Dwarf', 2),
        ('Herald of Gloom', 3),
        ('Minotaur Mage', 3),
        ('Reality Reaver', 3),
        ('Souleater', 3),
        ('Orc', 2),
        ('Askarak Prince', 3),
        ('Dworc Voodoomaster', 2)
    ) AS d(name, difficulty)
WHERE c.name = d.name;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE creatures DROP COLUMN difficulty;
-- +goose StatementEnd 