-- +goose Up
-- +goose StatementBegin
UPDATE creatures c
SET difficulty = d.difficulty
FROM (VALUES
    ('Corrupted Ghost', 1),
    ('Corrupted Skeleton', 1),
    ('Imperial', 1),
    ('Muglex Clan Assassin', 1),
    ('Muglex Clan Footman', 1),
    ('Stag', 1),
    ('Infernoid Blob', 2),
    ('Infernoid Hound', 2),
    ('Infernoid Soul', 2),
    ('Infernoid Spiritual', 2),
    ('Lizard Commander', 2),
    ('Lizard Executioner', 2),
    ('Lizard Henchman', 2),
    ('Lizard Magician', 2),
    ('Lizard Swordmaster', 2),
    ('Pirate Cook', 2),
    ('Pirate Gunner', 2),
    ('Pirate Navigator', 2),
    ('Pirate Quartermaster', 2),
    ('Sea Captain', 2),
    ('Hawk Hopper', 3),
    ('Ink Splash', 3),
    ('Bluebeak', 4),
    ('Bramble Wyrmling', 4),
    ('Cinder Wyrmling', 4),
    ('Crusader', 4),
    ('Crypt Mage', 4),
    ('Cyclursus', 4),
    ('Dworc Shadowstalker', 4),
    ('Gloom Maw', 4),
    ('Headwalker', 4),
    ('Lion Hydra', 4),
    ('Night Harpy', 4),
    ('Norcferatu Heartless', 4),
    ('Norcferatu Nightweaver', 4),
    ('Orclops Bloodbreaker', 4),
    ('Raubritter Chastener', 4),
    ('Raubritter Marksman', 4),
    ('Raubritter Skirmisher', 4),
    ('Roaming Dread', 4),
    ('Shell Drake', 4),
    ('Varg', 4),
    ('Creepy Crawler', 5),
    ('Crypt Construct', 5),
    ('Crypt Fiend', 5),
    ('Haunted Hunter', 5),
    ('Walking Dread', 5)
) AS d(name, difficulty)
WHERE c.name = d.name;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
UPDATE creatures SET difficulty = NULL WHERE name IN (
    'Corrupted Ghost',
    'Corrupted Skeleton',
    'Imperial',
    'Muglex Clan Assassin',
    'Muglex Clan Footman',
    'Stag',
    'Infernoid Blob',
    'Infernoid Hound',
    'Infernoid Soul',
    'Infernoid Spiritual',
    'Lizard Commander',
    'Lizard Executioner',
    'Lizard Henchman',
    'Lizard Magician',
    'Lizard Swordmaster',
    'Pirate Cook',
    'Pirate Gunner',
    'Pirate Navigator',
    'Pirate Quartermaster',
    'Sea Captain',
    'Hawk Hopper',
    'Ink Splash',
    'Bluebeak',
    'Bramble Wyrmling',
    'Cinder Wyrmling',
    'Crusader',
    'Crypt Mage',
    'Cyclursus',
    'Dworc Shadowstalker',
    'Gloom Maw',
    'Headwalker',
    'Lion Hydra',
    'Night Harpy',
    'Norcferatu Heartless',
    'Norcferatu Nightweaver',
    'Orclops Bloodbreaker',
    'Raubritter Chastener',
    'Raubritter Marksman',
    'Raubritter Skirmisher',
    'Roaming Dread',
    'Shell Drake',
    'Varg',
    'Creepy Crawler',
    'Crypt Construct',
    'Crypt Fiend',
    'Haunted Hunter',
    'Walking Dread'
);
-- +goose StatementEnd
